apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packagebuilds.build.luet.io
spec:
  group: build.luet.io
  version: v1alpha1
  names:
    kind: PackageBuild
    plural: packagebuilds
  scope: Namespaced
  subresources:
    status: {}
