apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: packagebuilds.luet.k8s.io
spec:
  group: luet.k8s.io
  version: v1alpha1
  names:
    kind: PackageBuild
    plural: packagebuilds
  scope: Namespaced
  subresources:
    status: {}
