apiVersion: v1
kind: Namespace
metadata:
  name: luet-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: luet-k8s
  namespace: luet-k8s
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: luet-k8s
rules:
- apiGroups:
  - build.luet.io
  resources:
  - packagebuilds/status
  - repobuilds/status
  verbs:
  - create
  - delete
  - patch
  - update
- apiGroups:
  - build.luet.io
  resources:
  - packagebuilds
  - repobuilds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create


---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: luet-k8s
    subjects:
    - kind: ServiceAccount
      name: luet-k8s
      namespace: luet-k8s
    roleRef:
      kind: ClusterRole
      name: luet-k8s
      apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
  namespace: luet-k8s
spec:
  selector:
    matchLabels:
      app: controller
  replicas: 1
  template:
    metadata:
      labels:
        app: controller
      name: controller
    spec:
      serviceAccountName: luet-k8s
      containers:
        - name: controller
          image: "quay.io/mudler/luet-k8s-controller:latest"
          imagePullPolicy: Always
          command: ["/usr/bin/luet-k8s"]
